name: "Build Android app"

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the main GitHub branch
        uses: actions/checkout@v3
      
      - name: Install npm dependencies
        run: |
          npm install

      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: android
          
      - name: List versions
        run: |
          cd android
          ./gradlew -version
          
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/

