name: "Build Android app"

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the main GitHub branch
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install

      - name: Build Android release
        run: |
          chmod +x android/gradlew
          cd android
          ./gradlew bundleRelease
          cd ..
          cp /home/runner/work/ChallengeTracker/ChallengeTracker/android/app/build/outputs/bundle/release/app-release.aab /home/runner/work/ChallengeTracker/ChallengeTracker/app-release.aab

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: List versions
        run: |
          cd android
          ./gradlew -version
          echo ${{ steps.package-version.outputs.current-version }}
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-${{ steps.package-version.outputs.current-version }}
          path: app-release.aab
